package csm

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// PublishMapThumbnails copies thumbsDir into the map_thumbnails/ folder of a
// cs2-server-manager git checkout at repoDir, commits it on a new branch and
// prints the push + `gh pr create` commands to run. It never pushes and never
// touches credentials: git's own configuration decides who the commit is by
// and whether the push dry run is allowed.
func PublishMapThumbnails(ctx context.Context, thumbsDir, repoDir, patchVersion string, w io.Writer) error {
	git := func(args ...string) (string, error) {
		cmd := exec.CommandContext(ctx, "git", append([]string{"-C", repoDir}, args...)...)
		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out
		err := cmd.Run()
		s := strings.TrimSpace(out.String())
		if err != nil {
			return s, fmt.Errorf("git %s: %v: %s", strings.Join(args, " "), err, s)
		}
		return s, nil
	}

	if _, err := exec.LookPath("git"); err != nil {
		return fmt.Errorf("git is not installed")
	}
	abs, err := filepath.Abs(repoDir)
	if err != nil {
		return err
	}
	repoDir = abs
	top, err := git("rev-parse", "--show-toplevel")
	if err != nil {
		return fmt.Errorf("%s is not a git checkout: %w", repoDir, err)
	}
	repoDir = top
	origin, err := git("remote", "get-url", "origin")
	origin = redactRemote(origin)
	if err != nil || !strings.Contains(origin, "cs2-server-manager") {
		return fmt.Errorf("%s does not look like a cs2-server-manager checkout (origin %q)", repoDir, origin)
	}
	if status, err := git("status", "--porcelain"); err != nil {
		return err
	} else if status != "" {
		return fmt.Errorf("%s has uncommitted changes; commit or stash them first", repoDir)
	}

	dst := filepath.Join(repoDir, "map_thumbnails")
	fmt.Fprintf(w, "[publish] Copying %s -> %s\n", thumbsDir, dst)
	copied, err := copyMapFiles(thumbsDir, dst)
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "[publish] %d files copied\n", copied)

	if status, err := git("status", "--porcelain", "--", "map_thumbnails"); err != nil {
		return err
	} else if status == "" {
		fmt.Fprintln(w, "[publish] map_thumbnails/ already matches the checkout; nothing to publish.")
		return nil
	}

	branch := "maps/update-" + time.Now().UTC().Format("20060102-150405")
	msg := "chore(maps): update map thumbnails and maps.json"
	if patchVersion != "" {
		msg += " for CS2 " + patchVersion
	}
	for _, args := range [][]string{
		{"checkout", "-b", branch},
		{"add", "--", "map_thumbnails"},
		{"commit", "-m", msg},
	} {
		if _, err := git(args...); err != nil {
			return err
		}
	}
	fmt.Fprintf(w, "[publish] Committed on branch %s in %s\n", branch, repoDir)

	if out, err := git("push", "--dry-run", "origin", branch); err != nil {
		fmt.Fprintf(w, "[publish] [!] Push dry run failed; you may not have push rights to %s:\n%s\n", origin, out)
		fmt.Fprintln(w, "[publish] The commit is kept locally. Push it from an account with access, or open a PR from a fork.")
		return fmt.Errorf("no push access to %s", origin)
	}

	fmt.Fprintln(w, "[publish] Push access confirmed. Nothing was pushed; to open the PR run:")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "  git -C %s push -u origin %s\n", shellQuote(repoDir), branch)
	prCmd := fmt.Sprintf("  gh pr create --base master --head %s --title %s --body %s",
		branch, shellQuote(msg), shellQuote("Map thumbnails and maps.json regenerated by `csm extract-map-data`."))
	if slug := githubSlug(origin); slug != "" {
		prCmd = fmt.Sprintf("  gh pr create --repo %s%s", slug, strings.TrimPrefix(prCmd, "  gh pr create"))
	}
	fmt.Fprintln(w, prCmd)
	return nil
}

// copyMapFiles copies the images and maps.json from src into dst. Files that
// only exist in dst are left alone. Copying a directory onto itself (csm run
// from inside the checkout) is a no-op.
func copyMapFiles(src, dst string) (int, error) {
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return 0, err
	}
	if si, err := os.Stat(src); err != nil {
		return 0, err
	} else if di, err := os.Stat(dst); err == nil && os.SameFile(si, di) {
		return 0, nil
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return 0, err
	}
	n := 0
	for _, e := range entries {
		name := e.Name()
		switch strings.ToLower(filepath.Ext(name)) {
		case ".png", ".webp", ".json":
		default:
			continue
		}
		if e.IsDir() {
			continue
		}
		data, err := os.ReadFile(filepath.Join(src, name))
		if err != nil {
			return n, err
		}
		if err := os.WriteFile(filepath.Join(dst, name), data, 0o644); err != nil {
			return n, err
		}
		n++
	}
	return n, nil
}

var remoteUserinfoRe = regexp.MustCompile(`://[^/@]+@`)

// redactRemote drops any user:token@ part of a remote URL before it is
// printed.
func redactRemote(remote string) string {
	return remoteUserinfoRe.ReplaceAllString(strings.TrimSpace(remote), "://")
}

var githubSlugRe = regexp.MustCompile(`github\.com[:/]([^/]+/[^/]+?)(\.git)?/?$`)

// githubSlug returns owner/repo for a GitHub remote URL.
func githubSlug(remote string) string {
	if m := githubSlugRe.FindStringSubmatch(strings.TrimSpace(remote)); m != nil {
		return m[1]
	}
	return ""
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
