#!/usr/bin/env python3
"""Third-party notices for csm's binary.

Builds csm, reads the Go modules compiled into it (`go version -m`), and
writes THIRD_PARTY_NOTICES.md with each module's license text from the
module cache, plus the Go runtime's license. MIT, BSD and Apache ask for
these notices to go with every copy of the binary; scripts/release.sh
attaches the file to each release.

    python3 scripts/third-party-notices.py          write THIRD_PARTY_NOTICES.md
    python3 scripts/third-party-notices.py --check  fail if it is out of date
"""
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "THIRD_PARTY_NOTICES.md")
MAIN = "./src/cmd/cs2-tui"
LICENSE_NAMES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING", "LICENCE", "LICENSE-MIT")

# Modules that ship no license file, checked by hand (2026-10-08): their
# README names the license. Check again when the version changes.
KNOWN = {
    "github.com/mattn/go-localereader": ("MIT", "Yasuhiro Matsumoto (a.k.a. mattn)"),  # README: "## License MIT"
}

MIT = """Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."""


def go(*args, env=None):
    return subprocess.run(["go", *args], cwd=ROOT, check=True, capture_output=True, text=True, env=env).stdout


def escaped(path):
    # The module cache spells capitals as !lower.
    return re.sub(r"[A-Z]", lambda m: "!" + m.group(0).lower(), path)


def main():
    cache = go("env", "GOMODCACHE").strip()
    goroot = go("env", "GOROOT").strip()
    with tempfile.TemporaryDirectory() as tmp:
        binary = os.path.join(tmp, "csm")
        env = dict(os.environ, GOOS="linux", GOARCH="amd64", CGO_ENABLED="0")
        go("build", "-o", binary, MAIN, env=env)
        info = go("version", "-m", binary)
    deps = []
    for line in info.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[0] == "dep":
            deps.append((parts[1], parts[2]))
        elif len(parts) >= 3 and parts[0] == "=>" and deps:
            deps[-1] = (parts[1], parts[2])  # a replace directive

    lines = [
        "# Third-party notices: csm",
        "",
        "CS2 Server Manager (csm) is under the PolyForm Noncommercial License 1.0.0 (LICENSE).",
        "Its binary is built with the Go modules below and the Go runtime, each under its own",
        "license, reproduced here as those licenses ask. Generated by",
        "`python3 scripts/third-party-notices.py`; do not edit by hand.",
        "",
    ]
    missing = []
    for path, version in sorted(deps):
        folder = os.path.join(cache, f"{escaped(path)}@{version}")
        text = ""
        for name in LICENSE_NAMES:
            f = os.path.join(folder, name)
            if os.path.isfile(f):
                text = open(f, encoding="utf-8", errors="replace").read().strip()
                break
        if not text and path in KNOWN:
            license_id, author = KNOWN[path]
            text = f"Copyright (c) {author}\n\n{MIT}\n\n(The module states {license_id} in its README and ships no license file; this is the standard {license_id} text.)"
        lines += [f"## {path} {version}", ""]
        if text:
            lines += ["```", text.replace("```", "'''"), "```", ""]
        else:
            missing.append(path)
            lines += ["_No license file in the module; see its repository._", ""]
    for name in ("LICENSE",):
        for base in (goroot, os.path.dirname(goroot)):
            f = os.path.join(base, name)
            if os.path.isfile(f):
                lines += ["## Go standard library and runtime", "", "```", open(f).read().strip(), "```", ""]
                break
        else:
            continue
        break
    text = "\n".join(lines)

    if "--check" in sys.argv:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        # The Go runtime's section is whichever Go builds it (its LICENSE text
        # changed in Go 1.23); releases write it fresh, so compare the modules.
        modules = lambda t: t.split("## Go standard library and runtime")[0]
        if modules(current) != modules(text):
            print("THIRD_PARTY_NOTICES.md is out of date: run python3 scripts/third-party-notices.py", file=sys.stderr)
            sys.exit(1)
        print(f"THIRD_PARTY_NOTICES.md is current ({len(deps)} modules).")
        return
    with open(OUT, "w") as f:
        f.write(text)
    print(f"Wrote THIRD_PARTY_NOTICES.md: {len(deps)} modules.")
    if missing:
        print("No license file found for: " + ", ".join(missing))


if __name__ == "__main__":
    main()
